apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkus-testlauf-4 
  janus-idp.io/tekton: quarkus-testlauf-4
  backstage.io/kubernetes-id: quarkus-testlauf-4
  backstage.io/kubernetes-namespace: quarkus-testlauf-4 
  app.kubernetes.io/part-of: quarkus-testlauf-4
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  