apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-testlauf-4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-testlauf-4 
  name: quarkus-testlauf-4
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-testlauf-4
    weight: 100 
